wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 32, 32, 32, 90]
    rows: [7, 10, 10, 4, 4, 90]
  refreshInterval: 1
  mods:
    europe_time:
      title: "Time"
      type: clocks
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Berlin: "Europe/Berlin"
        CET: "CET"
        PST: "PST8PDT"
        PNT, MST: "MST"
        CST: "CST6CDT"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
    docker:
      title: "Docker"
      type: docker
      enabled: true
      labelColor: lightblue
      position:
        top: 1
        left: 0
        height: 2
        width: 1
      refreshInterval: 1s
    resourceusage:
      title: "Resources"
      cpuCombined: true
      enabled: true
      position:
        top: 3
        left: 0
        height: 1
        width: 1
      refreshInterval: 1s
      showCPU: true
      showMem: true
      showSwp: false